name: FlooNetwork
main: com.maienm.FlooNetwork.FlooNetwork
version: 0.0.1
author: MaienM
dev-url: 
softdepend: [LWC]
description: >
             Move around the way REAL wizzards do!
commands:
  fn:
    description: Get FlooNetwork info.
    permission: floonetwork.command
permissions:
  floonetwork.*:
    description: All Floo Network permissions.
    children:
      floonetwork.use.*: true
      floonetwork.travel.*: true
      floonetwork.create: true
      floonetwork.destroy.*: true
      floonetwork.command.*: true
  floonetwork.user:
    description: Sensible defaults for users.
    children:
      floonetwork.use.*: true
      floonetwork.travel: true
      floonetwork.create: true
      floonetwork.destroy: true
      floonetwork.command.list: true
  floonetwork.admin:
    description: Sensible defauls for admins.
    children:
      floonetwork.*: true
  floonetwork.use.*:
    description: Can use any Floo Network fireplace.
    children:
      floonetwork.use.other: true
  floonetwork.use:
    description: Can use a Floo Network fireplace made by themself.
  floonetwork.use.other:
    description: Can use any Floo Network fireplace.
    children:
      floonetwork.use: true
  floonetwork.travel.*:
    description: Can travel to any Floo Network fireplace.
    children:
      floonetwork.travel.other: true
  floonetwork.travel:
    description: Can travel to a Floo Network fireplace made by themself.
  floonetwork.travel.other:
    description: Can travel to any Floo Network fireplace.
    children:
      floonetwork.travel: true
  floonetwork.create:
    description: Can create a Floo Network fireplace.
  floonetwork.destroy.*:
    description: Can destroy any Floo Network fireplace.
    children: 
      floonetwork.destroy.other: true
  floonetwork.destroy:
    description: Can destroy a Floo Network fireplace made by themself.
  floonetwork.destroy.other:
    description: Can destroy any Floo Network fireplace.
    children: 
      floonetwork.destroy: true
  floonetwork.command.*:
    description: Can use any Floo Network command.
    children:
      floonetwork.command.list: true
      floonetwork.command.warp.*: true
      floonetwork.command.reload: true
  floonetwork.command:
    description: Can use the /fn command. This command makes no sense without any of the floonetwork.command.* permissions.
  floonetwork.command.list:
    description: Can get a list of all Floo Network fireplaces they have access to.
    children:
      floonetwork.command: true
  floonetwork.command.warp.*:
    description: Can warp any player to any Floo Network fireplace.
    children: 
      floonetwork.command.warp.other.anywhere: true
  floonetwork.command.warp:
    description: Can warp themself to a Floo Network fireplace made by themself.
    children:
      floonetwork.command: true
  floonetwork.command.warp.anywhere:
    description: Can warp themself to any Floo Network fireplace.
    children: 
      floonetwork.command.warp: true
  floonetwork.command.warp.other:
    description: Can warp other players to a Floo Network fireplace made by themself.
    children: 
      floonetwork.command.warp: true
  floonetwork.command.warp.other.anywhere:
    description: Can warp other players to any Floo Network fireplace.
    children: 
      floonetwork.command.warp: true
      floonetwork.command.warp.anywhere: true
      floonetwork.command.warp.other: true
  floonetwork.command.reload:
    description: Can reload the Floo Network config.
    children:
      floonetwork.command: true
